# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=cn.frkovo.rhythmcv2
archives_base_name=RhythMC-MOD
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.6+1.21.11

# Loom 1.17 requires JVM >= 21 for the Gradle daemon
org.gradle.java.home=C:/Users/16055/.jdks/azul-21.0.10
